name: cd-pull-and-run-docker-image-aws-ec2
on:
  workflow_run:
    workflows: ["cd-build-publish-docker-image"]
    types:
      - completed
jobs:
  run:
    runs-on: self-hosted
    steps:      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1
      - name: Pull Docker image
        run: sudo docker pull 'matiasmiguez/ml-demo-project:latest'
      - name: Run Docker Container at port 8080
        run: sudo docker run -d -p 8080:8080 --name ml-demo-project-container 'matiasmiguez/ml-demo-project'
