name: cd-build-publich-docker-image

on:
  workflow_run:
    workflows: ["ci-build-python-app"]
    types: 
      - completed
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login into DockerHub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME --password $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t matiasmiguez/ml-demo-project:latest . --file Dockerfile
    - name: Push to DockerHub
      run: docker push matiasmiguez/ml-demo-project:latest
    
  run:
  
    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull docker pull matiasmiguez/ml-demo-project:latest
    - name: Delete Old docker container
      run: sudo docker rm -f ml-demo-project-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name ml-demo-project-container matiasmiguez/ml-demo-project
  
