name: cd-build-publish-docker-image

on:
  workflow_run:
    workflows: ["ci-build-and-test-python-app"]
    types: 
      - completed
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login into DockerHub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME --password $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t matiasmiguez/ml-demo-project:latest . --file Dockerfile
    - name: Push to DockerHub
      run: docker push matiasmiguez/ml-demo-project:latest
  
